name: "acji_dbt"
version: "1.0.0"
config-version: 2

profile: "acji"

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  acji_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
